// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwebltRgWVv7i_i5ReeoY1K3UKwwF2FU',
    appId: '1:319710447950:android:4552bb9d524b911ba2f61f',
    messagingSenderId: '319710447950',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-YvGGlTSZh1IcX9OraGn_csnPfpRlM4',
    appId: '1:319710447950:ios:33256ef735bf5158a2f61f',
    messagingSenderId: '319710447950',
    projectId: 'redbus-3ec46',
    storageBucket: 'redbus-3ec46.appspot.com',
    androidClientId: '319710447950-2ltd456epi1h5g6igoaqsiv2efj4cepg.apps.googleusercontent.com',
    iosClientId: '319710447950-7o1oapai6u596493ehbee68t5a4l5ijk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomeet',
  );
}
