// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeU9MfUSDno7nH2_LMAGNHFuj8uIBRcz4',
    appId: '1:1046116791776:web:e0493bbf81d7e9b55de785',
    messagingSenderId: '1046116791776',
    projectId: 'formen-application',
    authDomain: 'formen-application.firebaseapp.com',
    storageBucket: 'formen-application.appspot.com',
    measurementId: 'G-20QEXW2J8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDytMD_n7J-4KQWc459E898n1J6GzA155o',
    appId: '1:1046116791776:android:a06f9a2bef237a125de785',
    messagingSenderId: '1046116791776',
    projectId: 'formen-application',
    storageBucket: 'formen-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMAubn-RPNtqBD-4JTq-YkeVi5Fq-MeBc',
    appId: '1:1046116791776:ios:55d0f140ef4ac9615de785',
    messagingSenderId: '1046116791776',
    projectId: 'formen-application',
    storageBucket: 'formen-application.appspot.com',
    iosBundleId: 'com.example.formen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMAubn-RPNtqBD-4JTq-YkeVi5Fq-MeBc',
    appId: '1:1046116791776:ios:51f9bf763d0da6485de785',
    messagingSenderId: '1046116791776',
    projectId: 'formen-application',
    storageBucket: 'formen-application.appspot.com',
    iosBundleId: 'com.example.gomeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeU9MfUSDno7nH2_LMAGNHFuj8uIBRcz4',
    appId: '1:1046116791776:web:a54efb296a460d105de785',
    messagingSenderId: '1046116791776',
    projectId: 'formen-application',
    authDomain: 'formen-application.firebaseapp.com',
    storageBucket: 'formen-application.appspot.com',
    measurementId: 'G-CZ8NGBN3DD',
  );
}
